AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function: 
     Runtime: java8
     MemorySize: 512
     Timeout: 30
     Environment:
       Variables:
         ORDERS_TABLE: !Ref OrdersTable
Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
       Name: id
       Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.chaitanya.aws.lambda.api.CreateOrderLambda::createOrder
      Policies:
       - DynamoDBCrudPolicy:
          TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  GetOrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.chaitanya.aws.lambda.api.ReadOrderLambda::getOrders
      Policies:
       - DynamoDBReadPolicy:
          TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
Outputs:
 CreateOrdersAPI:
   Description: "This is API Gateway end point URL for create orders function"
   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
 CreateOrdersFunction:
   Description: "Create Order Lambda Function ARN"
   Value: !GetAtt CreateOrderFunction.Arn
 CreateOrdersIAMRole:
   Description: "Create Order Lambda Function IAM Roles ARN"
   Value: !GetAtt CreateOrderFunctionRole.Arn
     
